// ─── Admin Service Layer ─────────────────────────────────────────────────────
// Mock data + fetch functions consumed by React Query on the admin dashboard.
// Realistic data modelling CreatorCashCow.com at ~6 months post-launch.
// ─────────────────────────────────────────────────────────────────────────────

import type {
  AdminUser,
  AdminCourse,
  AdminPDF,
  AdminLiveSession,
  AdminBooking,
  AdminPayment,
  KpiCard,
  AnalyticsData,
  ContentBlock,
  SystemSettings,
  AdminDashboardData,
} from "@/types/admin";

// ─── Mock Users ─────────────────────────────────────────────────────────────

const mockUsers: AdminUser[] = [
  {
    id: "u-001",
    full_name: "Jordan Mitchell",
    email: "jordan@example.com",
    role: "user",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    created_at: "2024-09-15T10:30:00Z",
    last_login: "2025-01-12T14:22:00Z",
    enrolled_courses: 3,
    total_spent: 547.0,
    status: "active",
  },
  {
    id: "u-002",
    full_name: "Samantha Lee",
    email: "sam.lee@example.com",
    role: "user",
    avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    created_at: "2024-10-02T08:15:00Z",
    last_login: "2025-01-11T09:40:00Z",
    enrolled_courses: 5,
    total_spent: 1249.0,
    status: "active",
  },
  {
    id: "u-003",
    full_name: "Marcus Chen",
    email: "marcus.c@example.com",
    role: "user",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
    created_at: "2024-10-20T16:45:00Z",
    last_login: "2025-01-10T20:10:00Z",
    enrolled_courses: 2,
    total_spent: 398.0,
    status: "active",
  },
  {
    id: "u-004",
    full_name: "Priya Patel",
    email: "priya@example.com",
    role: "user",
    avatar_url: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    created_at: "2024-11-05T12:00:00Z",
    last_login: "2025-01-08T18:30:00Z",
    enrolled_courses: 4,
    total_spent: 897.0,
    status: "active",
  },
  {
    id: "u-005",
    full_name: "Tyler Brooks",
    email: "tyler.b@example.com",
    role: "user",
    avatar_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    created_at: "2024-11-15T09:20:00Z",
    last_login: null,
    enrolled_courses: 1,
    total_spent: 199.0,
    status: "suspended",
  },
  {
    id: "u-006",
    full_name: "Elena Rodriguez",
    email: "elena.r@example.com",
    role: "user",
    avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop",
    created_at: "2024-12-01T11:10:00Z",
    last_login: "2025-01-12T08:55:00Z",
    enrolled_courses: 3,
    total_spent: 746.0,
    status: "active",
  },
  {
    id: "u-007",
    full_name: "CC Mendel",
    email: "cc@creatorcashcow.com",
    role: "admin",
    avatar_url: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop",
    created_at: "2024-09-01T00:00:00Z",
    last_login: "2025-01-12T16:00:00Z",
    enrolled_courses: 0,
    total_spent: 0,
    status: "active",
  },
  {
    id: "u-008",
    full_name: "Aisha Johnson",
    email: "aisha.j@example.com",
    role: "user",
    avatar_url: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=100&h=100&fit=crop",
    created_at: "2024-12-18T14:30:00Z",
    last_login: "2025-01-11T22:15:00Z",
    enrolled_courses: 2,
    total_spent: 448.0,
    status: "active",
  },
];

// ─── Mock Courses ───────────────────────────────────────────────────────────

const mockCourses: AdminCourse[] = [
  {
    id: "c-001",
    title: "UGC Mastery",
    description: "Create viral user-generated content that brands pay premium rates for.",
    price: 199.0,
    currency: "USD",
    thumbnail_url: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400&h=250&fit=crop",
    modules: [
      { id: "m-001", title: "What Is UGC?", description: "Introduction to UGC landscape", video_url: "https://youtube.com/embed/demo1", order: 1 },
      { id: "m-002", title: "Building Your Portfolio", description: "Creating a portfolio that converts", video_url: "https://youtube.com/embed/demo2", order: 2 },
      { id: "m-003", title: "Landing Brand Deals", description: "Outreach and negotiation tactics", video_url: "https://youtube.com/embed/demo3", order: 3 },
    ],
    enrollments: 142,
    revenue: 28258.0,
    created_at: "2024-09-10T08:00:00Z",
    updated_at: "2025-01-05T12:00:00Z",
    status: "published",
  },
  {
    id: "c-002",
    title: "TikTok Shop Blueprint",
    description: "Build and scale a profitable TikTok Shop from scratch.",
    price: 249.0,
    currency: "USD",
    thumbnail_url: "https://images.unsplash.com/photo-1611605698335-8b1569810432?w=400&h=250&fit=crop",
    modules: [
      { id: "m-004", title: "TikTok Shop Setup", description: "Account setup and optimization", video_url: "https://youtube.com/embed/demo4", order: 1 },
      { id: "m-005", title: "Product Sourcing", description: "Finding winning products", video_url: "https://youtube.com/embed/demo5", order: 2 },
      { id: "m-006", title: "Scaling with Ads", description: "Paid advertising strategies", video_url: "https://youtube.com/embed/demo6", order: 3 },
      { id: "m-007", title: "Affiliate Army", description: "Recruiting affiliates at scale", video_url: "https://youtube.com/embed/demo7", order: 4 },
    ],
    enrollments: 98,
    revenue: 24402.0,
    created_at: "2024-09-15T08:00:00Z",
    updated_at: "2025-01-03T10:00:00Z",
    status: "published",
  },
  {
    id: "c-003",
    title: "Dropshipping Accelerator",
    description: "Zero to $10K/mo dropshipping with modern fulfillment strategies.",
    price: 299.0,
    currency: "USD",
    thumbnail_url: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=250&fit=crop",
    modules: [
      { id: "m-008", title: "Store Setup", description: "Shopify store from scratch", video_url: "https://youtube.com/embed/demo8", order: 1 },
      { id: "m-009", title: "Supplier Network", description: "Building reliable supply chains", video_url: "https://youtube.com/embed/demo9", order: 2 },
      { id: "m-010", title: "Facebook Ads", description: "Profitable ad campaigns", video_url: "https://youtube.com/embed/demo10", order: 3 },
    ],
    enrollments: 67,
    revenue: 20033.0,
    created_at: "2024-10-01T08:00:00Z",
    updated_at: "2024-12-28T09:00:00Z",
    status: "published",
  },
  {
    id: "c-004",
    title: "Digital Product Empire",
    description: "Create, launch, and scale digital products that generate passive income.",
    price: 199.0,
    currency: "USD",
    thumbnail_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=250&fit=crop",
    modules: [
      { id: "m-011", title: "Product Ideation", description: "Finding profitable niches", video_url: "https://youtube.com/embed/demo11", order: 1 },
      { id: "m-012", title: "Design & Package", description: "Professional product creation", video_url: "https://youtube.com/embed/demo12", order: 2 },
    ],
    enrollments: 89,
    revenue: 17711.0,
    created_at: "2024-10-15T08:00:00Z",
    updated_at: "2025-01-02T14:00:00Z",
    status: "published",
  },
  {
    id: "c-005",
    title: "Platform Owner Playbook",
    description: "Build your own platform and own your audience forever.",
    price: 349.0,
    currency: "USD",
    thumbnail_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop",
    modules: [
      { id: "m-013", title: "Platform Architecture", description: "Choosing your tech stack", video_url: "https://youtube.com/embed/demo13", order: 1 },
      { id: "m-014", title: "Monetization Models", description: "Revenue streams deep dive", video_url: "https://youtube.com/embed/demo14", order: 2 },
      { id: "m-015", title: "Growth & Scale", description: "Organic + paid user acquisition", video_url: "https://youtube.com/embed/demo15", order: 3 },
    ],
    enrollments: 45,
    revenue: 15705.0,
    created_at: "2024-11-01T08:00:00Z",
    updated_at: "2025-01-04T16:00:00Z",
    status: "published",
  },
];

// ─── Mock PDFs ──────────────────────────────────────────────────────────────

const mockPDFs: AdminPDF[] = [
  {
    id: "p-001",
    title: "Creator Monetization Cheat Sheet",
    description: "50+ monetization strategies for content creators in a single guide.",
    file_url: "/files/creator-cheatsheet.pdf",
    cover_url: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=300&h=400&fit=crop",
    price: 29.0,
    currency: "USD",
    downloads: 312,
    revenue: 9048.0,
    created_at: "2024-09-20T08:00:00Z",
    status: "published",
  },
  {
    id: "p-002",
    title: "Brand Deal Email Templates",
    description: "12 plug-and-play email templates that land brand deals.",
    file_url: "/files/brand-deal-templates.pdf",
    cover_url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=300&h=400&fit=crop",
    price: 19.0,
    currency: "USD",
    downloads: 478,
    revenue: 9082.0,
    created_at: "2024-10-05T08:00:00Z",
    status: "published",
  },
  {
    id: "p-003",
    title: "TikTok Algorithm Decoded",
    description: "Deep-dive analysis of the TikTok algorithm with actionable growth hacks.",
    file_url: "/files/tiktok-algorithm.pdf",
    cover_url: "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=300&h=400&fit=crop",
    price: 39.0,
    currency: "USD",
    downloads: 195,
    revenue: 7605.0,
    created_at: "2024-11-10T08:00:00Z",
    status: "published",
  },
];

// ─── Mock Live Sessions ─────────────────────────────────────────────────────

const mockLiveSessions: AdminLiveSession[] = [
  {
    id: "ls-001",
    title: "Q1 2025 Creator Trends Live",
    description: "Deep-dive into what's working now for creators.",
    scheduled_date: "2025-02-15T18:00:00Z",
    duration_minutes: 90,
    attendees: 78,
    max_capacity: 200,
    is_replay_available: false,
    replay_url: null,
    status: "upcoming",
  },
  {
    id: "ls-002",
    title: "UGC Portfolio Review Session",
    description: "Live portfolio reviews and feedback from CC Mendel.",
    scheduled_date: "2025-01-25T19:00:00Z",
    duration_minutes: 60,
    attendees: 45,
    max_capacity: 50,
    is_replay_available: false,
    replay_url: null,
    status: "upcoming",
  },
  {
    id: "ls-003",
    title: "Holiday Revenue Masterclass",
    description: "Strategies for maximizing Q4 creator revenue.",
    scheduled_date: "2024-12-10T18:00:00Z",
    duration_minutes: 120,
    attendees: 156,
    max_capacity: 200,
    is_replay_available: true,
    replay_url: "https://youtube.com/watch?v=replay1",
    status: "completed",
  },
  {
    id: "ls-004",
    title: "TikTok Shop Live Workshop",
    description: "Hands-on TikTok Shop setup and optimization.",
    scheduled_date: "2024-11-20T17:00:00Z",
    duration_minutes: 90,
    attendees: 112,
    max_capacity: 150,
    is_replay_available: true,
    replay_url: "https://youtube.com/watch?v=replay2",
    status: "completed",
  },
];

// ─── Mock Bookings ──────────────────────────────────────────────────────────

const mockBookings: AdminBooking[] = [
  {
    id: "b-001",
    user_id: "u-002",
    user_name: "Samantha Lee",
    user_email: "sam.lee@example.com",
    scheduled_date: "2025-01-20T14:00:00Z",
    duration_minutes: 120,
    status: "confirmed",
    payment_status: "success",
    amount: 499.0,
    meeting_url: "https://zoom.us/j/meeting1",
    created_at: "2025-01-05T09:30:00Z",
  },
  {
    id: "b-002",
    user_id: "u-004",
    user_name: "Priya Patel",
    user_email: "priya@example.com",
    scheduled_date: "2025-01-28T10:00:00Z",
    duration_minutes: 120,
    status: "pending",
    payment_status: "success",
    amount: 499.0,
    meeting_url: null,
    created_at: "2025-01-10T15:20:00Z",
  },
  {
    id: "b-003",
    user_id: "u-006",
    user_name: "Elena Rodriguez",
    user_email: "elena.r@example.com",
    scheduled_date: "2025-02-05T16:00:00Z",
    duration_minutes: 120,
    status: "confirmed",
    payment_status: "success",
    amount: 499.0,
    meeting_url: "https://zoom.us/j/meeting3",
    created_at: "2025-01-12T11:00:00Z",
  },
  {
    id: "b-004",
    user_id: "u-001",
    user_name: "Jordan Mitchell",
    user_email: "jordan@example.com",
    scheduled_date: "2024-12-15T13:00:00Z",
    duration_minutes: 120,
    status: "completed",
    payment_status: "success",
    amount: 499.0,
    meeting_url: null,
    created_at: "2024-12-01T08:45:00Z",
  },
  {
    id: "b-005",
    user_id: "u-003",
    user_name: "Marcus Chen",
    user_email: "marcus.c@example.com",
    scheduled_date: "2024-11-30T15:00:00Z",
    duration_minutes: 120,
    status: "cancelled",
    payment_status: "failed",
    amount: 499.0,
    meeting_url: null,
    created_at: "2024-11-20T10:00:00Z",
  },
];

// ─── Mock Payments ──────────────────────────────────────────────────────────

const mockPayments: AdminPayment[] = [
  {
    id: "pay-001",
    user_id: "u-002",
    user_name: "Samantha Lee",
    user_email: "sam.lee@example.com",
    date: "2025-01-10T12:00:00Z",
    item: "Platform Owner Playbook",
    item_type: "course",
    amount: 349.0,
    currency: "USD",
    status: "success",
    method: "stripe",
    transaction_id: "txn_3QhXk2AbcDef001",
    invoice_url: "/invoices/inv-001.pdf",
  },
  {
    id: "pay-002",
    user_id: "u-006",
    user_name: "Elena Rodriguez",
    user_email: "elena.r@example.com",
    date: "2025-01-09T15:30:00Z",
    item: "1:1 Mentorship Session",
    item_type: "mentorship",
    amount: 499.0,
    currency: "USD",
    status: "success",
    method: "stripe",
    transaction_id: "txn_3QhXk2AbcDef002",
    invoice_url: "/invoices/inv-002.pdf",
  },
  {
    id: "pay-003",
    user_id: "u-001",
    user_name: "Jordan Mitchell",
    user_email: "jordan@example.com",
    date: "2025-01-08T09:15:00Z",
    item: "Creator Monetization Cheat Sheet",
    item_type: "pdf",
    amount: 29.0,
    currency: "USD",
    status: "success",
    method: "paypal",
    transaction_id: "txn_pp_AbcDef003",
    invoice_url: "/invoices/inv-003.pdf",
  },
  {
    id: "pay-004",
    user_id: "u-008",
    user_name: "Aisha Johnson",
    user_email: "aisha.j@example.com",
    date: "2025-01-07T18:45:00Z",
    item: "TikTok Shop Blueprint",
    item_type: "course",
    amount: 249.0,
    currency: "USD",
    status: "success",
    method: "stripe",
    transaction_id: "txn_3QhXk2AbcDef004",
    invoice_url: "/invoices/inv-004.pdf",
  },
  {
    id: "pay-005",
    user_id: "u-003",
    user_name: "Marcus Chen",
    user_email: "marcus.c@example.com",
    date: "2025-01-06T11:20:00Z",
    item: "UGC Mastery",
    item_type: "course",
    amount: 199.0,
    currency: "USD",
    status: "success",
    method: "stripe",
    transaction_id: "txn_3QhXk2AbcDef005",
    invoice_url: "/invoices/inv-005.pdf",
  },
  {
    id: "pay-006",
    user_id: "u-004",
    user_name: "Priya Patel",
    user_email: "priya@example.com",
    date: "2025-01-05T14:00:00Z",
    item: "Brand Deal Email Templates",
    item_type: "pdf",
    amount: 19.0,
    currency: "USD",
    status: "success",
    method: "paypal",
    transaction_id: "txn_pp_AbcDef006",
    invoice_url: "/invoices/inv-006.pdf",
  },
  {
    id: "pay-007",
    user_id: "u-005",
    user_name: "Tyler Brooks",
    user_email: "tyler.b@example.com",
    date: "2025-01-04T10:10:00Z",
    item: "Dropshipping Accelerator",
    item_type: "course",
    amount: 299.0,
    currency: "USD",
    status: "failed",
    method: "stripe",
    transaction_id: "txn_3QhXk2AbcDef007",
    invoice_url: null,
  },
  {
    id: "pay-008",
    user_id: "u-002",
    user_name: "Samantha Lee",
    user_email: "sam.lee@example.com",
    date: "2025-01-03T16:30:00Z",
    item: "1:1 Mentorship Session",
    item_type: "mentorship",
    amount: 499.0,
    currency: "USD",
    status: "success",
    method: "stripe",
    transaction_id: "txn_3QhXk2AbcDef008",
    invoice_url: "/invoices/inv-008.pdf",
  },
  {
    id: "pay-009",
    user_id: "u-006",
    user_name: "Elena Rodriguez",
    user_email: "elena.r@example.com",
    date: "2025-01-02T08:50:00Z",
    item: "TikTok Algorithm Decoded",
    item_type: "pdf",
    amount: 39.0,
    currency: "USD",
    status: "pending",
    method: "stripe",
    transaction_id: "txn_3QhXk2AbcDef009",
    invoice_url: null,
  },
  {
    id: "pay-010",
    user_id: "u-008",
    user_name: "Aisha Johnson",
    user_email: "aisha.j@example.com",
    date: "2025-01-01T20:00:00Z",
    item: "Digital Product Empire",
    item_type: "course",
    amount: 199.0,
    currency: "USD",
    status: "success",
    method: "stripe",
    transaction_id: "txn_3QhXk2AbcDef010",
    invoice_url: "/invoices/inv-010.pdf",
  },
];

// ─── Mock KPIs ──────────────────────────────────────────────────────────────

const mockKpis: KpiCard[] = [
  {
    label: "Total Revenue",
    value: "$131,844",
    change: 18.3,
    trend: "up",
    icon: "CurrencyDollarIcon",
  },
  {
    label: "Total Users",
    value: "847",
    change: 12.7,
    trend: "up",
    icon: "UsersIcon",
  },
  {
    label: "Active Enrollments",
    value: "441",
    change: 8.4,
    trend: "up",
    icon: "AcademicCapIcon",
  },
  {
    label: "Mentorship Bookings",
    value: "23",
    change: -5.2,
    trend: "down",
    icon: "CalendarDaysIcon",
  },
  {
    label: "PDF Downloads",
    value: "985",
    change: 22.1,
    trend: "up",
    icon: "DocumentArrowDownIcon",
  },
  {
    label: "Avg Order Value",
    value: "$217",
    change: 3.6,
    trend: "up",
    icon: "ShoppingCartIcon",
  },
];

// ─── Mock Analytics ─────────────────────────────────────────────────────────

const mockAnalytics: AnalyticsData = {
  revenue_over_time: [
    { month: "Jul 2024", courses: 4200, pdfs: 800, mentorship: 1500, total: 6500 },
    { month: "Aug 2024", courses: 6800, pdfs: 1200, mentorship: 2000, total: 10000 },
    { month: "Sep 2024", courses: 9500, pdfs: 1800, mentorship: 3000, total: 14300 },
    { month: "Oct 2024", courses: 12200, pdfs: 2400, mentorship: 3500, total: 18100 },
    { month: "Nov 2024", courses: 14800, pdfs: 3100, mentorship: 4000, total: 21900 },
    { month: "Dec 2024", courses: 18500, pdfs: 3800, mentorship: 5500, total: 27800 },
    { month: "Jan 2025", courses: 21000, pdfs: 4200, mentorship: 6000, total: 31200 },
  ],
  user_growth: [
    { month: "Jul 2024", new_users: 45, total_users: 45 },
    { month: "Aug 2024", new_users: 78, total_users: 123 },
    { month: "Sep 2024", new_users: 112, total_users: 235 },
    { month: "Oct 2024", new_users: 134, total_users: 369 },
    { month: "Nov 2024", new_users: 156, total_users: 525 },
    { month: "Dec 2024", new_users: 178, total_users: 703 },
    { month: "Jan 2025", new_users: 144, total_users: 847 },
  ],
  conversion_funnel: [
    { stage: "Visitors", count: 24500, rate: 100 },
    { stage: "Sign-ups", count: 847, rate: 3.46 },
    { stage: "Free Content", count: 612, rate: 72.3 },
    { stage: "First Purchase", count: 441, rate: 52.1 },
    { stage: "Repeat Purchase", count: 187, rate: 42.4 },
  ],
  top_products: [
    { id: "c-001", title: "UGC Mastery", type: "course", revenue: 28258, units_sold: 142 },
    { id: "c-002", title: "TikTok Shop Blueprint", type: "course", revenue: 24402, units_sold: 98 },
    { id: "c-003", title: "Dropshipping Accelerator", type: "course", revenue: 20033, units_sold: 67 },
    { id: "c-004", title: "Digital Product Empire", type: "course", revenue: 17711, units_sold: 89 },
    { id: "c-005", title: "Platform Owner Playbook", type: "course", revenue: 15705, units_sold: 45 },
    { id: "p-002", title: "Brand Deal Email Templates", type: "pdf", revenue: 9082, units_sold: 478 },
    { id: "p-001", title: "Creator Monetization Cheat Sheet", type: "pdf", revenue: 9048, units_sold: 312 },
  ],
  mrr: 31200,
  arr: 374400,
  churn_rate: 4.2,
  avg_order_value: 217,
};

// ─── Mock Content Blocks ────────────────────────────────────────────────────

const mockContentBlocks: ContentBlock[] = [
  {
    id: "cb-001",
    page: "landing",
    section: "Hero",
    title: "Hero Headline",
    body: "From Zero to Platform Owner — Build Your Creator Empire with CC Mendel",
    updated_at: "2025-01-10T12:00:00Z",
    published: true,
  },
  {
    id: "cb-002",
    page: "landing",
    section: "Hero",
    title: "Hero Subheadline",
    body: "5 premium courses. Expert mentorship. Digital products. Everything you need to monetize your creativity.",
    updated_at: "2025-01-10T12:00:00Z",
    published: true,
  },
  {
    id: "cb-003",
    page: "landing",
    section: "Live Offer",
    title: "Limited Offer Banner",
    body: "New Year Bundle — All 5 courses for $799 (save $496). Offer expires soon.",
    updated_at: "2025-01-01T00:00:00Z",
    published: true,
  },
  {
    id: "cb-004",
    page: "course",
    section: "Course Page",
    title: "Money-Back Guarantee",
    body: "Try any course risk-free for 30 days. If you're not satisfied, we'll refund every penny.",
    updated_at: "2024-12-15T10:00:00Z",
    published: true,
  },
  {
    id: "cb-005",
    page: "mentorship",
    section: "Booking Page",
    title: "Mentorship CTA",
    body: "Book a 2-hour 1:1 session with CC Mendel and get personalized strategies for your creator business.",
    updated_at: "2024-12-20T14:00:00Z",
    published: true,
  },
];

// ─── Mock System Settings ───────────────────────────────────────────────────

const mockSettings: SystemSettings = {
  site_name: "CreatorCashCow",
  tagline: "Build Your Creator Empire",
  support_email: "support@creatorcashcow.com",
  stripe_mode: "test",
  maintenance_mode: false,
  signup_enabled: true,
  mentorship_enabled: true,
  mentorship_price: 499,
  default_currency: "USD",
};

// ─── Fetch Function ─────────────────────────────────────────────────────────

/** Fetch all admin dashboard data — consumed by React Query */
export async function fetchAdminDashboard(): Promise<AdminDashboardData> {
  const response = await fetch("/api/admin/dashboard", {
    method: "GET",
    headers: { "Content-Type": "application/json" },
    credentials: "include",
  });

  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: "Failed to load admin data" }));
    throw new Error(err.error || "Failed to load admin data");
  }

  const data = await response.json();
  return data;
}

